<a href="https://colab.research.google.com/github/LiTaokui/TensorFlow-Example/blob/main/Example05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
state = {
    0 : "burger",
    1 : "pizza",
    2 : "hotdog"
}
state

{0: 'burger', 1: 'pizza', 2: 'hotdog'}

In [5]:
A = np.array([[0.2,0.6,0.2], [0.3,0.0,0.7], [0.5,0.0,0.5]])
A

array([[0.2, 0.6, 0.2],
       [0.3, 0. , 0.7],
       [0.5, 0. , 0.5]])

## random walk ##

In [8]:
n = 15
start_state = 0
print(state[start_state], "--->", end="")
prev_state = start_state

while n-1:
  curr_state = np.random.choice([0,1,2], p=A[prev_state])
  print(state[curr_state], "--->", end="")
  prev_state = curr_state
  n-=1
print("stop")

burger --->pizza --->hotdog --->burger --->pizza --->hotdog --->hotdog --->hotdog --->burger --->hotdog --->burger --->pizza --->burger --->pizza --->hotdog --->stop


## approach 1 : monte carlo ##

In [10]:
steps = 10**6
start_state = 0
pi = np.array([0,0,0])
prev_state = start_state

i = 0
while i<steps:
  curr_state = np.random.choice([0,1,2], p=A[prev_state])
  pi[curr_state]+=1
  prev_state = curr_state
  i+=1

print("pi=", pi/steps)

pi= [0.351775 0.210836 0.437389]


## approach 2 : repeated matrix multiplication ##

In [12]:
steps = 10**3
A_n = A

i = 0
while i<steps:
  A_n = np.matmul(A_n,A)
  i+=1

print("A^n = \n", A_n, "\n")
print("pi =", A_n[0])

A^n = 
 [[0.35211268 0.21126761 0.43661972]
 [0.35211268 0.21126761 0.43661972]
 [0.35211268 0.21126761 0.43661972]] 

pi = [0.35211268 0.21126761 0.43661972]


## approach 3 : find left e-vectors ##

In [16]:
import scipy.linalg
values, left = scipy.linalg.eig(A, right = False, left = True)

print("left eigen vectors = \n", left, "\n")
print("eigen values = \n", values)

left eigen vectors = 
 [[-0.58746336+0.j          0.16984156+0.35355339j  0.16984156-0.35355339j]
 [-0.35247801+0.j         -0.67936622+0.j         -0.67936622-0.j        ]
 [-0.72845456+0.j          0.50952467-0.35355339j  0.50952467+0.35355339j]] 

eigen values = 
 [ 1.  +0.j        -0.15+0.3122499j -0.15-0.3122499j]


In [17]:
pi = left[:,0]
pi_normalized = [x/np.sum(pi).real for x in pi]
pi_normalized

[(0.3521126760563379-0j), (0.21126760563380304-0j), (0.4366197183098591-0j)]

## P(pizza ---> hotdog ---> hotdog ---> burger) = ? ##

In [18]:
def find_prob(seq,A, pi):
  start_state = seq[0]
  prob =pi[start_state]
  prev_state = start_state
  for i in range(1, len(seq)):
    curr_state = seq[i]
    prob *= A[prev_state][curr_state]
    prev_state = curr_state
  return prob

print(find_prob([1,2,2,0], A, pi_normalized))

(0.03697183098591553+0j)
